services:
  service1:
    build: ./app/service1
    ports:
      - "8001:8000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  service2:
    build: ./app/service2
    ports:
      - "8002:8000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  promtail:
    image: grafana/promtail:2.1.0
    volumes:
      - ./promtail/promtail-config.yml:/etc/promtail/promtail.yml
      - /var/log:/var/log
    ports:
      - "9080:9080"

  loki:
    image: grafana/loki:2.7.1
    volumes:
      - ./loki/loki-config.yml:/etc/loki/loki.yml
    ports:
      - "3100:3100"

  grafana:
    image: grafana/grafana:9.5.1
    ports:
      - "3000:3000"
    depends_on:
      - loki
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
