server:
  http_listen_port: 9080
  grpc_listen_port: 0

scrape_configs:
  - job_name: 'docker-logs'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    pipeline_stages:
      - json:
          expressions:
            log: log
    relabel_configs:
      - source_labels: [__meta_docker_container_label_com_docker_swarm_service_name]
        target_label: job
      - source_labels: [__meta_docker_container_name]
        target_label: container
      - source_labels: [__meta_docker_container_id]
        target_label: container_id

ingester:
  chunk_target_size: 1048576
  chunk_idle_period: 5m
  max_chunk_age: 1h
  max_inflight_chunks_per_stream: 20
  max_chunk_size: 10485760
  rate_limit:
    ingest_rate_limit: 20MB/s
